export enum WsOrdersTypes {
    WS_CONNECT_PROFILE = 'WS_CONNECT_PROFILE',
    WS_DISCONNECT_PROFILE = 'WS_DISCONNECT_PROFILE',
    WS_CONNECTING_PROFILE = 'WS_CONNECTING_PROFILE',
    WS_OPEN_PROFILE = 'WS_OPEN_PROFILE',
    WS_CLOSE_PROFILE = 'WS_CLOSE_PROFILE',
    WS_MESSAGE_PROFILE = 'WS_MESSAGE_PROFILE',
    WS_ERROR_PROFILE = 'WS_ERROR_PROFILE'
}
