export const SELECT_BUN = 'SELECT_BUN';
export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const DELETE_INGREDIENT = 'DELETE_INGREDIENT';
export const SORT_INGREDIENTS = 'SORT_INGREDIENTS';
export const RESET_INGREDIENTS = 'RESET_INGREDIENTS';